### ISSUE TITLE
Nullpointers :/

### ISSUE THREAD

**Issue by faluck** [libgdx/gdx-realsense#9]
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at vire.MainClass.create(MainClass.java:57)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

I'm getting this when i run the samplecode

handData = handModule.CreateOutput();

is throwing a nullpointer exception but everything seems fine..

**Comment by alexzhang7801** [comment]
I also met this issue as below, How to resolve it?
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.badlogic.realsense.RealSenseTest.create(RealSenseTest.java:29)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by alexzhang7801** [comment]
Hi faluck,
Could you resolve this issue?

**Comment by faluck** [comment]
No unfortunately not :/

**Comment by alexzhang7801** [comment]
How to locate the problem？have not point thinking. wowo.
http://prntscr.com/76gqa3
